name = "Farlands"
author = "SillviaTV, AmyMialee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8fea5bca4d4eaad2a718d14ce54c2067924173d3fa4a6245b64a74720c875b17"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
