name = "Farlands"
author = "SillviaTV, AmyMialee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffaea6622b072c95045f45db39fd90a9d77f9ee3a138f484b2c9f738b3c1b688"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
