name = "Farlands"
author = "SillviaTV, AmyMialee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ffdc72dd834026f6f72208754479de64f5e6ab007241f75e62f99e74a3f2dfd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
