name = "Farlands"
author = "SillviaTV, AmyMialee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2560cf18d30a684e61a97d5ea1b6c5e8dd36c16bccce1dc8109269a20ea641e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
