name = "Farlands"
author = "SillviaTV, AmyMialee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa778d200f7464b79862a8860578a4f903be1233b66635345a2038036185ea3f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
