name = "Farlands"
author = "SillviaTV, AmyMialee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e24203c4d46d7c4653215c410353f15e41dbeb90252fcd1dc88d1ddfa2260baa"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
